#
# Spice Spectator, made by SpiceDev.
# https://www.spigotmc.org/resources/spice-spectator-ssp.100970/
# https://github.com/Spice-Development/SpiceSpectator
#

quit-item-name: 'WATCH' # This is the item you will receive after entering spectator mode
quit-item-custom-name: '&cExit spectator mode' # This is the name of the item that you will receive when in spectator mode
quit-item-slot: 8 # This is the slot that the item will appear in your inventory
